apiVersion: v1
kind: ConfigMap
metadata:
  name: loadbalance-expressions
  namespace: hello-world
data:
  hello-world: |
    sum(
      nginx_connections_active{container="nginx-exporter", namespace="%namespace%", pod="%pod-name%"}
    ) +
    sum(
      rate(container_cpu_usage_seconds_total{namespace="%namespace%", pod="%pod-name%"}[5m])
    ) +
    sum(
      container_memory_working_set_bytes{namespace="%namespace%", pod="%pod-name%"} / 1024 / 1024
    )
