apiVersion: v1
kind: ConfigMap
metadata:
  name: loadbalance-expressions
  namespace: hello-world
data:
  hello-world: |
    avg by (kubernetes_pod_name) (
      (
        rate(nginx_ingress_controller_requests{kubernetes_pod_name=~"%pod-name%", namespace="%namespace%"}[2m]) * 25 +
        rate(container_cpu_usage_seconds_total{kubernetes_pod_name=~"%pod-name%", namespace="%namespace%"}[2m]) * 50 +
        (container_memory_usage_bytes{kubernetes_pod_name=~"%pod-name%", namespace="%namespace%"} / 1024 / 1024) * 25
      )
    )