apiVersion: v1
kind: Service
metadata:
  name: client-metrics
  namespace: client
  labels:
    app: client
spec:
  ports:
  - port: 9113
    targetPort: metrics
    name: metrics
  selector:
    app: client