apiVersion: v1
kind: Service
metadata:
  name: hello-world-metrics
  namespace: hello-world
  labels:
    app: hello-world
spec:
  ports:
  - port: 9113
    targetPort: metrics
    name: metrics
  selector:
    app: hello-world