apiVersion: v1
kind: Namespace
metadata:
  name: hello-world
  labels:
    dns.peak/domain: "hello.peak"
    dns.peak/loadbalance: "configmap.loadbalance-expressions.hello-world"
    dns.peak/loadbalance-mode: excludeoverloaded
    dns.peak/overload-threshold: 1.5