apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: client
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
    - client
  selector:
    matchLabels:
      app: client
  endpoints:
  - port: metrics
    interval: 15s
  - port: metrics
    path: /metrics
    interval: 15s
    honorLabels: true
    metricRelabelings:
    - action: keep
      regex: "container_.*|pod_.*"
      sourceLabels: [__name__]
