apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service
  namespace: post-service
  labels:
    app: post-service
    dns.peak/domain: post.service.peak
    dns.peak/loadbalance: configmap.loadbalance-expressions.post-service
    dns.peak/loadbalance-mode: excludeoverloaded
    dns.peak/overload-threshold: "1.5"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: post-service
  template:
    metadata:
      labels:
        app: post-service
    spec:
      containers:
        - name: post-service
          image: localhost:5000/post:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          env:
            - name: PORT
              value: "80"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: post-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: post-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_HOST
              value: "$POST_POSTGRES_HOST"
            - name: POSTGRES_DB
              value: "$POST_POSTGRES_DB"
            - name: POSTGRES_PORT
              value: "$POST_POSTGRES_PORT"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: post-secrets
                  key: JWT_SECRET
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: post-service
  namespace: post-service
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: post-service