apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: post-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: $POST_POSTGRES_PORT
          env:
            - name: POSTGRES_DB
              value: "$POST_POSTGRES_DB"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: post-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: post-secrets
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: post-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: post-service
spec:
  ports:
    - port: $AUTH_POSTGRES_PORT
      targetPort: $AUTH_POSTGRES_PORT
  selector:
    app: postgres