apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-upload
  namespace: image
  labels:
    dns.peak/domain: "image.service.peak"
    dns.peak/only-top: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-upload
  template:
    metadata:
      labels:
        app: image-upload
    spec:
      containers:
        - name: image-upload
          image: localhost:5000/imageupload:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          env:
            - name: PORT
              value: "80"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: image-secrets
                  key: JWT_SECRET
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: image-upload-service
  namespace: image
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: image-upload