apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: peakdns-binding
subjects:
  - kind: ServiceAccount
    name: peakdns
    namespace: default
roleRef:
  kind: ClusterRole
  name: peakdns-role
  apiGroup: rbac.authorization.k8s.io