apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: peakdns-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "nodes", "namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods", "nodes"]
    verbs: ["get", "list"]