apiVersion: v1
kind: ConfigMap
metadata:
  name: peakdns-settings
data:
  settings.ini: |
    [logging]
    path=./log.txt
    logLevel=5
    [server]
    port=53
    tcpThreads=10
    udpThreads=10
    [requester]
    server=1.1.1.1
    path=./zones
    timeoutMs=2000
    maxRetries=3
    maxConcurrent=100
    [cache]
    cleanupInterval=1000
    maxEntries=1000
    [provider]
    prometheusDNSName=prometheus-operated.monitoring.svc.cluster.local