apiVersion: v1
kind: Service
metadata:
  name: peakdns
spec:
  clusterIP: 10.96.0.11
  ports:
    - port: 53
      protocol: UDP
      name: dns-udp
    - port: 53
      protocol: TCP
      name: dns-tcp
  selector:
    app: peakdns