FROM node:20.18.1-alpine3.19
RUN echo "http://dl-cdn.alpinelinux.org/alpine/v3.14/main" >> /etc/apk/repositories
RUN apk update
RUN apk add --no-cache libssl1.1


WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

COPY main.js .

ENV PORT=80
ENV CORS_ORIGIN=*

EXPOSE 80

CMD ["node", "main.js"]