apiVersion: v1
kind: Namespace
metadata:
  name: dev-service
  labels:
    dns.peak/domain: "client.peak"
    dns.peak/only-top: "true"
---
apiVersion: v1
kind: Pod
metadata:
  name: nodejs-dev
  namespace: dev-service
spec:
  containers:
    - name: nodejs
      image: node:20-alpine
      workingDir: /app
      command: ["/bin/sh", "-c"]
      args:
        - |
          npm install -g vite
          npm install --force
          vite --host
      volumeMounts:
        - name: app-source
          mountPath: /app
      ports:
        - containerPort: 5173
  volumes:
    - name: app-source
      hostPath:
        path: /root/client
        type: Directory