apiVersion: v1
kind: Namespace
metadata:
  name: dev-service
  labels:
    dns.peak/domain: "auth.peak"
    dns.peak/only-top: "false"
---
apiVersion: v1
kind: Pod
metadata:
  name: nodejs-dev
  namespace: dev-service
  labels:
    dns.peak/domain: "client.peak"
    dns.peak/only-top: "true"
spec:
  containers:
    - name: nodejs
      image: node:20-alpine
      workingDir: /app
      command: ["/bin/sh", "-c"]
      args:
        - |
          cp package*.json /tmp/
          cd /tmp
          npm install --force
          cd /app
          cp -r /tmp/node_modules .
          npm install -g vite
          vite --port 80 --host --force
      volumeMounts:
        - name: app-source
          mountPath: /app
        - name: node-modules
          mountPath: /app/node_modules
      ports:
        - containerPort: 80
  volumes:
    - name: app-source
      hostPath:
        path: /root/client
        type: Directory
    - name: node-modules
      emptyDir: {}