apiVersion: v1
kind: Service
metadata:
  name: nfs-server
  namespace: video
spec:
  selector:
    app: nfs-server
  ports:
    - name: nfs
      port: 2049
      targetPort: 2049
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server
  namespace: video
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-server
  template:
    metadata:
      labels:
        app: nfs-server
    spec:
      containers:
        - name: nfs-server
          image: itsthenetwork/nfs-server-alpine:latest
          ports:
            - name: nfs
              containerPort: 2049
          securityContext:
            privileged: true
          env:
            - name: SHARED_DIRECTORY
              value: /nfsshare
          volumeMounts:
            - name: nfs-data
              mountPath: /nfsshare
      volumes:
        - name: nfs-data
          emptyDir: {}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  namespace: video
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /nfsshare
    server: nfs-server.video.svc.cluster.local
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
  namespace: video
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi