apiVersion: v1
kind: Secret
metadata:
  name: video-secrets
  namespace: video
type: Opaque
stringData:
  POSTGRES_USER: $VIDEO_POSTGRES_USER
  POSTGRES_PASSWORD: $VIDEO_POSTGRES_PASSWORD
  JWT_SECRET: $JWT_SECRET
  rabbitmq-url: "amqp://user:password@rabbitmq.video.svc.cluster.local:5672"