apiVersion: v1
kind: Secret
metadata:
  name: video-secrets
  namespace: video
type: Opaque
stringData:
  POSTGRES_USER: auth
  POSTGRES_PASSWORD: pass1234
  JWT_SECRET: supersecrettoken
  rabbitmq-url: "amqp://user:password@rabbitmq.video.svc.cluster.local:5672"