apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-upload
  namespace: video
  labels:
    dns.peak/domain: video.upload.peak
    dns.peak/loadbalance: configmap.loadbalance-expressions.video-service
    dns.peak/loadbalance-mode: excludeoverloaded
    dns.peak/overload-threshold: "1.5"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: video-upload
  template:
    metadata:
      labels:
        app: video-upload
    spec:
      containers:
        - name: video-upload
          image: localhost:5000/videoupload:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          env:
            - name: PORT
              value: "80"
            - name: STORAGE_PATH
              value: "/nfsshare"
            - name: POSTGRES_HOST
              value: "postgres.video.svc.cluster.local"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: video-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: video-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: "video"
            - name: POSTGRES_PORT
              value: "5432"
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: video-secrets
                  key: rabbitmq-url
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: video-secrets
                  key: JWT_SECRET
          volumeMounts:
            - name: nfs-storage
              mountPath: /nfsshare
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 15
      volumes:
        - name: nfs-storage
          persistentVolumeClaim:
            claimName: nfs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: video-upload-service
  namespace: video
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: video-upload