apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-processing
  namespace: video
spec:
  replicas: 3
  selector:
    matchLabels:
      app: video-processing
  template:
    metadata:
      labels:
        app: video-processing
    spec:
      containers:
        - name: video-processing
          image: localhost:5000/videoprocessing:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          env:
            - name: PORT
              value: "80"
            - name: STORAGE_PATH
              value: "/nfsshare"
            - name: POSTGRES_HOST
              value: "$VIDEO_POSTGRES_HOST"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: video-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: video-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: "$VIDEO_POSTGRES_DB"
            - name: POSTGRES_PORT
              value: "$VIDEO_POSTGRES_PORT"
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: video-secrets
                  key: rabbitmq-url
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: video-secrets
                  key: JWT_SECRET
          volumeMounts:
            - name: nfs-storage
              mountPath: /nfsshare
      volumes:
        - name: nfs-storage
          persistentVolumeClaim:
            claimName: nfs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: video-processing-service
  namespace: video
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: video-processing