apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics
  namespace: user
---
apiVersion: v1
kind: Service
metadata:
  name: metrics
  namespace: user
  labels:
    app: metrics
spec:
  selector:
    app: metrics
  ports:
  - name: metrics
    port: 9100
    targetPort: 9100
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: user
spec:
  selector:
    matchLabels:
      app: metrics
  template:
    metadata:
      labels:
        app: metrics
    spec:
      serviceAccountName: metrics
      hostNetwork: true
      hostPID: true
      containers:
      - name: node-exporter
        image: prom/node-exporter:latest
        ports:
        - containerPort: 9100
        volumeMounts:
        - name: proc
          mountPath: /host/proc
          readOnly: true
        - name: sys
          mountPath: /host/sys
          readOnly: true
      volumes:
      - name: proc
        hostPath:
          path: /proc
      - name: sys
        hostPath:
          path: /sys