apiVersion: v1
kind: Secret
metadata:
  name: user-secrets
  namespace: user
type: Opaque
stringData:
  POSTGRES_USER: $USER_POSTGRES_USER
  POSTGRES_PASSWORD: $USER_POSTGRES_PASSWORD
  JWT_SECRET: $JWT_SECRET