apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: auth-service
type: Opaque
stringData:
  POSTGRES_USER: $AUTH_POSTGRES_USER
  POSTGRES_PASSWORD: $AUTH_POSTGRES_PASSWORD
  JWT_SECRET: $JWT_SECRET
